# 端口
server:
  port: 8061

# 属性
spring:
  application:
    name: combination-server-rabbitmq

  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password:  admin
    # 是否启用【发布确认】
    publisher-confirms: true
    # 指定一个请求能处理多少个消息
    listener:
      simple:
        # 限流（海量数据，同时只能过来一条）
        prefetch: 1
        # 自动签收auto  手动 manual  默认自动签收
        acknowledge-mode: auto
        retry:
          # 开启重试机制
          enabled: true
          # 重试次数
          # max-attempts: 5
          # 最大间隔时间
          # max-interval: 20000
          # 重试间隔时间（单位毫秒）
          # initial-interval: 3000
          #乘子  重试间隔*乘子得出下次重试间隔  3s  6s  12s  24s  此处24s>20s  走20s
          # multiplier: 2
          # 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        # default-requeue-rejected: false

eureka:
  client:
    service-url:
      # eureka配置信息
      defaultZone: http://localhost:8000/eureka/
  # 注册中心地址实例id
  instance:
    prefer-ip-address: true
